language: java
jdk:
  - oraclejdk8

script:
  - sh build-jar.sh
  - sh src/test/resources/test.sh

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh rars.jar
